
title: Eclipse Co Arma Docs
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for the Eclipse Co Arma Boys.

baseurl: "/eclipse-arma-munitions"
url: "https://alipali737.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pdmosses/just-the-docs@combination-rec-nav

aux_links:
  "See Source on Github":
    - "//github.com/alipali737/eclipse-arma-munitions"

toggle_color_scheme: dark
toggle_auto_mode: true
